spring.application.name=novo
# Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/novo
spring.datasource.username=lukinhaslk
spring.datasource.password=tekocfw1806

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true